apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test-route
    app.kubernetes.io/runtime: camel
  name: test-route
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-route
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-route
    spec:
      containers:
      - image: test-route:1.0-SNAPSHOT
        name: test-route
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
