apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: test-route
    app.kubernetes.io/runtime: camel
  name: test-route
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: test-route
  type: ClusterIP
